package triangle

import (
	"bufio"
	"fmt"
	//"github.com/denautonomepirat/shapefile/triangle"
	"github.com/jonas-p/go-shp"
	"github.com/kellydunn/golang-geo"
	"log"
	"os"
	"strconv"
	"strings"
)

type Point struct {
	Id int
	X  float64
	Y  float64
}

func ImportShapefile(s string) map[int]*Point {
	// open a shapefile for reading

	r := make(map[int]*Point)
	shape, err := shp.Open(s)
	if err != nil {
		log.Fatal(err)
	}
	defer shape.Close()

	// loop through all features in the shapefile
	for shape.Next() {

		_, p := shape.Shape()
		switch p := p.(type) {
		case *shp.Polygon:

			fmt.Printf("No of vertexes in Polygon: %v\n", p.NumPoints)
			fmt.Printf("No of parts in Polygon: %v\n", p.NumParts)

			//Create .node file
			node, err := os.Create("triangle/temp.node")
			if err != nil {
				panic(err)
			}
			defer node.Close()

			nodeWriter := bufio.NewWriter(node)

			line := fmt.Sprintf("#Generated by importShapefile.go\n%v 2 0 0\n", p.NumPoints)
			_, err = nodeWriter.WriteString(line)
			if err != nil {
				panic(err)
			}

			for i := int32(0); i < p.NumPoints; i++ {
				//fmt.Printf("%v %v %v\n", i-p.Parts[i], p.Points[i].X, p.Points[i].Y)
				line = fmt.Sprintf("%v %v %v\n", i, p.Points[i].X, p.Points[i].Y)
				_, err := nodeWriter.WriteString(line)
				if err != nil {
					panic(err)
				}
			}
			nodeWriter.Flush()

			//Create .poly file
			poly, err := os.Create("triangle/temp.poly")
			if err != nil {
				panic(err)
			}
			defer poly.Close()

			polyWriter := bufio.NewWriter(poly)

			line = fmt.Sprintf("#Generated by importShapefile.go\n0 2 0 0\n")
			_, err = polyWriter.WriteString(line)
			if err != nil {
				panic(err)
			}

			line = fmt.Sprintf("%v 0\n", p.NumPoints-p.NumParts)
			_, err = polyWriter.WriteString(line)
			if err != nil {
				panic(err)
			}
			segmentno := 0

			for i := int32(0); i < p.NumParts; i++ {
				endOfPart := int32(0)
				if i >= p.NumParts-1 {
					endOfPart = p.NumPoints
				} else {
					endOfPart = p.Parts[i+1]
				}
				for j := p.Parts[i]; j < endOfPart-2; j++ {
					line = fmt.Sprintln(segmentno, j, j+1)
					_, err = polyWriter.WriteString(line)
					if err != nil {
						panic(err)
					}
					segmentno++

				}
				line = fmt.Sprintln(segmentno, endOfPart-2, p.Parts[i])
				_, err = polyWriter.WriteString(line)
				if err != nil {
					panic(err)
				}
				segmentno++
			}

			line = fmt.Sprintf("#Holes\n75\n")
			_, err = polyWriter.WriteString(line)
			if err != nil {
				panic(err)
			}
			//Find a point inside the hole
			//Since we know that the polygons are clockwise to indicate outer ring
			//this approach should be safe'ish still starting at index 1 though
			for i := int32(1); i < p.NumParts; i++ {
				var found bool = false
				for j := int32(0); found == false; j++ {
					temp := p.Points[p.Parts[i]+j]
					pA := geo.NewPoint(temp.X, temp.Y)
					temp = p.Points[p.Parts[i]+j+1]
					pB := geo.NewPoint(temp.X, temp.Y)
					temp = p.Points[p.Parts[i]+j+1]
					pC := geo.NewPoint(temp.X, temp.Y)
					diff := pB.BearingTo(pA) - pB.BearingTo(pC)
					if diff > 40 && diff < 120 {
						found = true
						pH := pB.PointAtDistanceAndBearing(0.002, diff) // create a point 2 meters inside the island

						line = fmt.Sprintln(i, pH.Lat(), pH.Lng())
						_, err = polyWriter.WriteString(line)
						if err != nil {
							panic(err)
						}
					}
				}

			}

			//Add holes

			polyWriter.Flush()

		default:
			fmt.Printf("unexpected type %T\n", p)
		}
		//Call triangle
		Triangulate()

		file, err := os.Open("triangle/temp.1.node") // For read access.
		if err != nil {
			log.Fatal(err)
		}
		defer file.Close()

		scanner := bufio.NewScanner(file)

		var foundFirst bool = false

		var numberOfPoints int64 = 0

		for scanner.Scan() {
			if scanner.Text()[0] != '#' {

				splitString := strings.Split(scanner.Text(), " ")

				for i := 0; i < len(splitString); i++ {
					if splitString[i] == " " || splitString[i] == "" {
						splitString = append(splitString[:i], splitString[i+1:]...)
						i--
					}
				}

				if !foundFirst {
					numberOfPoints, _ = strconv.ParseInt(splitString[0], 10, 64)
					foundFirst = true
				} else {
					id, _ := strconv.ParseInt(splitString[0], 10, 64)
					x, _ := strconv.ParseFloat(splitString[1], 64)
					y, _ := strconv.ParseFloat(splitString[2], 64)
					point := &Point{Id: int(id), X: x, Y: y}
					r[int(id)] = point
				}
			}

		}
		fmt.Println(numberOfPoints)

		if err := scanner.Err(); err != nil {
			log.Fatal(err)
		}
	}
	return r
}
